export const LIST_DETAILHOSO_REQUEST =
  "listChiTietHoSoKyReducer/LIST_DETAILHOSO_REQUEST";
export const LIST_DETAILHOSO_SUCCESS =
  "listChiTietHoSoKyReducer/LIST_DETAILHOSO_SUCCESS";
export const LIST_DETAILHOSO_FAILED =
  "listChiTietHoSoKyReducer/LIST_DETAILHOSO_FAILED";
