export const USER_RESETLOGIN_REQUEST = "userResetLoginReducer/USER_RESETLOGIN_REQUEST";
export const USER_RESETLOGIN_SUCCESS = "userResetLoginReducer/USER_RESETLOGIN_SUCCESS";
export const USER_RESETLOGIN_FAILED = "userResetLoginReducer/USER_RESETLOGIN_FAILED";
